// <auto-generated />
using System;
using ChartHub.BackupApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChartHub.BackupApi.Persistence.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    [Migration("20260326010330_MakeRecordIdNullable")]
    partial class MakeRecordIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChartHub.BackupApi.Persistence.SongSnapshotEntity", b =>
                {
                    b.Property<long>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SongId"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DiffBand")
                        .HasColumnType("integer");

                    b.Property<int?>("DiffBass")
                        .HasColumnType("integer");

                    b.Property<int?>("DiffDrums")
                        .HasColumnType("integer");

                    b.Property<int?>("DiffGuitar")
                        .HasColumnType("integer");

                    b.Property<int?>("DiffKeys")
                        .HasColumnType("integer");

                    b.Property<int?>("DiffVocals")
                        .HasColumnType("integer");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameFormat")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastReconciledRunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("RecordUpdatedUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("SongJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("SongId");

                    b.HasIndex("Artist");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DiffDrums");

                    b.HasIndex("DiffGuitar");

                    b.HasIndex("FileId");

                    b.HasIndex("GameFormat");

                    b.HasIndex("Genre");

                    b.HasIndex("GroupId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastSyncedUtc");

                    b.HasIndex("RecordId")
                        .IsUnique();

                    b.HasIndex("RecordUpdatedUnix");

                    b.HasIndex("Title");

                    b.HasIndex("IsDeleted", "LastReconciledRunId");

                    b.ToTable("SongSnapshots");
                });

            modelBuilder.Entity("ChartHub.BackupApi.Persistence.SyncStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
