name: Validate OpenAPI

on:
  push:
    tags:
      - 'v*'

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Redocly CLI
        run: npm install --global @redocly/cli

      - name: Lint OpenAPI document
        run: redocly lint openapi.yaml
